SearXNG 2026.7.3-21773bbb2
...
... INFORMATION
... "/etc/searxng/settings.yml" does not exist, creating from template...
...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
[INFO] Starting granian (main PID: 1)
[INFO] Listening at: http://:::8080
[INFO] Spawning worker-1 with PID: 856
[INFO] Started worker-1
[INFO] Shutting down granian
[INFO] Stopping worker-1
[INFO] Stopped worker-1
[INFO] Granian shutdown completed, see ya!
